Migrated the daily checkin apis
shamiri-health/rafi-api-v2 pull request #32
Opened 2024-04-29 11:39 UTC by UwaoEvan

**What i did**
- Migrated daily checkin apis

2024-04-30 07:52 UTC, tindNan commented on src/routes/daily-check-in/index.ts
> +import CHECKINPROMTS from "../../../static/daily_checkin_prompts.json";
typo :)

2024-04-30 08:37 UTC, tindNan commented on src/routes/daily-check-in/index.ts
> +                        // do something
we ought to log this as an error and cancel the transaction altogether.

2024-04-30 08:41 UTC, UwaoEvan commented
Yeah..I'm still working on it.

On Tue, Apr 30, 2024, 11:37 Shadrack Lilan ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In src/routes/daily-check-in/index.ts
> <https://github.com/shamiri-health/rafi-api-v2/pull/32#discussion_r1584367616>
> :
>
> > +                        howAreYouFeeling: request.body.how_are_you_feeling,
> +                        moodDescription: request.body.mood_description,
> +                        moodDescriptionCauseCategory1: request.body.mood_description_cause_category_1,
> +                        moodDescriptionCauseResponse1: request.body.mood_description_cause_response_1,
> +                        moodDescriptionCauseCategory2: request.body.mood_description_cause_category_2,
> +                        moodDescriptionCauseResponse2: request.body.mood_description_cause_response_2,
> +                        moodDescriptionCauseCategory3: request.body.mood_description_cause_category_3,
> +                        moodDescriptionCauseResponse3: request.body.mood_description_cause_response_3,
> +                        userId
> +                    });
> +                    const rewardHubRecord = await trx.query.userRewardHub.findFirst({
> +                        where: eq(userRewardHub.userId, userId)
> +                    });
> +
> +                    if (!rewardHubRecord) {
> +                        // do something
>
> we ought to log this as an error and cancel the transaction altogether.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/shamiri-health/rafi-api-v2/pull/32#pullrequestreview-2030616606>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AR2XWL4ZWTJEBF44UNBWGC3Y75J6FAVCNFSM6AAAAABG6E4VFKVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDAMZQGYYTMNRQGY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-05-06 11:42 UTC, tindNan commented on src/routes/daily-check-in/index.ts
> +      const checkinRecords = await fastify.db.query.dailyCheckIn.findFirst({
rename this to `checkInRecord`. `checkInRecords` implies that we are returning a list and we only need to return 1

2024-05-06 11:49 UTC, tindNan commented on src/lib/userRewardHub.ts
> +  record: RewardHub,
I think you may want to use something like `typeof userAchievementRecord.$inferSelect` instead of creating the `RewardHub` schema using typebox if you are sure that you will be using the the value from  the select results in LINE 120 of daily-check-in/index.ts

2024-05-06 11:51 UTC, UwaoEvan commented on src/lib/userRewardHub.ts
> +  record: RewardHub,
Enyewe. Thanks.

2024-05-06 12:03 UTC, tindNan requested changes

2024-05-06 12:03 UTC, tindNan commented on test/routes/daily-check-in/check-if-levels-unlock.test.ts
> +  t.notSame(achievement.gems, lastAchievementRecord.gems);
let's make the checks more strict. 

I think by this point we know that the gems + levels have gone up to a certain amount. So let's test the actual value.

2024-05-06 12:03 UTC, tindNan commented on test/routes/daily-check-in/check-if-streak-updates.test.ts
> +    await app.db.delete(user).where(eq(user.id, sampleUser.id));
might be good to also delete the human as well

2024-05-06 12:03 UTC, tindNan commented on test/routes/daily-check-in/check-if-streak-updates.test.ts
> +  t.notSame(lastAchievementRecord.gems, body.gems);
same comment on strictness as above.

2024-05-06 12:03 UTC, tindNan commented on test/routes/daily-check-in/create-daily-checkin-record.test.ts
> +  t.equal(checkInRecord.howAreYouFeeling, payload.how_are_you_feeling);
There is an assertion function I believe called `t.match` or something that you can use to check that all the key-value pairs in the `payload` object are a valid subset of the `checkInRecord` result from the db call.

2024-05-06 12:15 UTC, UwaoEvan commented on src/lib/userRewardHub.ts
> +  record: RewardHub,
Yeah.

2024-05-06 12:16 UTC, UwaoEvan commented on src/lib/userRewardHub.ts
> +const gemsLevel: GemLevel = {
Okay

2024-05-06 12:16 UTC, UwaoEvan commented on src/database/0004_luxuriant_taskmaster.sql
Alright.

2024-05-06 12:16 UTC, UwaoEvan commented on src/lib/userRewardHub.ts
> +  const totalGems: number = record.gems + nGems;
Alright.

2024-05-06 12:42 UTC, UwaoEvan commented on src/lib/userRewardHub.ts
> +    if (totalGems >= gemsNextLevel) {
Done.

2024-05-08 06:34 UTC, tindNan commented on src/database/schema.ts
> +  userId: integer("user_id").references(() => user.id),
Why do we need this column in the `rewardHubRecord` table?

Also there is a missing sql script to add this column to the actual SQL table.

What I would do:

1. delete the files starting with `0009_`
2. undo the changes in `_journal.json`
3. Given this new addition run `yarn generate`. This will generate an sql file with the necessary sql script to add this column.
4. Afterwards you can generate the custom migration file as you have already done and put in the custom SQL statement to update the `userId` field in the `userAchievement` table.

2024-05-08 06:35 UTC, tindNan commented on src/database/schema.ts
> +  level: integer("level"),
same comment as above about running `yarn generate`

2024-05-08 06:37 UTC, tindNan commented on src/lib/userRewardHub.ts
> +  const NUMBER_OF_SECONDS = 86400; // seconds in 24 hours
might be easier to use milliseconds?

You can do 
`const DAY_IN_MILLISECONDS = 24 * 60 * 60 * 1000 // a day in milliseconds`

That way you don't have to do the division in line 103

2024-05-09 11:56 UTC, closed without merging